### ISSUE TITLE
DisplayVersion not read correctly

### ISSUE THREAD

**Issue by thewillwilson** [Mr-Tbone/AoV#2]
Hi!

Just been digging into the script before deploying it, but just noticed the script doesn't actually read the DisplayVersion from the registry correctly even when it's there, therefore showing 0.0.0.0.

It looks like it's caused by the install script looking for `$AppKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$ProfileName"`  with $profilename being `$ProfileName    = "$company AoV Device Tunnel"`

Whereas the reg is actually being written with the GUID suffix by `$AddRemKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$guid"` therefore isn't actually finding the key

**Comment by Mr-Tbone** [comment]
Thanks for reporting! Now fixed in version 1.3
